### ISSUE TITLE
socket not being close

### ISSUE THREAD

**Issue by impegoraro** [nitroshare/qhttpengine#12]
In the previous version of the library the process method in QObjectHandler used to close the socket, and I don't think is being closed now, you think is no longer needed ? or is it being close somewhere else ?

**Comment by nathan-osman** [comment]
Thanks for pointing that out. Somehow that got missed when I rewrote that block of code. I'll try to get that fixed within the next day or two.

**Comment by impegoraro** [comment]
No problem.
I'm testing closing the socket in QHttpServer after the processing is done, this way it applies to both the QHttpHandler and QFilesystemHandler, if you don't agree tell me, otherwise I could send a pull request.

**Comment by nathan-osman** [comment]
Sorry for the delay in getting back to you. Yes, a pull request for closing the socket in `QHttpServer` would be fine. Thanks!

**Comment by nathan-osman** [comment]
This has now been fixed.
