### ISSUE TITLE
can't compile against msvc2010

### ISSUE THREAD

**Issue by windymindy** [nitroshare/qhttpengine#17]
--- qlocalfile.cpp ---
28 #elif defined(Q_OS_WIN32)
29 #  include <aclapi.h>
30 #  include <fileapi.h>
31 #endif

Line 30: can't open fileapi.h

Here is a quick workaround.

 #elif defined(Q_OS_WIN32)
 #  include <aclapi.h>
-#  include <fileapi.h>
+#  //include <fileapi.h>
+#  include <windows.h>
 #endif

**Comment by nathan-osman** [comment]
Thanks, this is fixed now.
