### ISSUE TITLE
please, replace cmake to qmake

### ISSUE THREAD

**Issue by TechComet** [nitroshare/qhttpengine#19]
Hi,

please, replace cmake to qmake

**Comment by nathan-osman** [comment]
[qmake is being deprecated](https://wiki.qt.io/Qt_build_systems_at_QtCon_2016) with the eventual intent of being replaced by CMake or QBS. There are no plans to switch build systems at this time.

**Comment by TechComet** [comment]
I did not know it

But qbs is very easy vs cmake
I'm need add the include to my project (no as lib) (I'm convert it)


all examples error
CMake Error at CMakeLists.txt:7 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "authclient".


CMake Error at CMakeLists.txt:18 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "authserver".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.5)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/techcomet/build/Qt/qhttpengine/examples/auth/CMakeFiles/CMakeOutput.log".

**Comment by nathan-osman** [comment]
The very first line of `CMakeLists.txt` is:

    cmake_minimum_required(VERSION 3.2.0)
