### ISSUE TITLE
Add qhttpengine to msys2 mingw package manager

### ISSUE THREAD

**Issue by droidmonkey** [nitroshare/qhttpengine#23]
https://github.com/msys2/msys2/wiki/Creating-Packages

In order to support building on windows, adding the qhttpengine library to the msys2/mingw package manager is critical. I could not find how to submit packages to the manager.

**Comment by nathan-osman** [comment]
I've submitted a pull request here to add the library: https://github.com/Alexpux/MINGW-packages/pull/3118

**Comment by nathan-osman** [comment]
This has been merged.
